export const OrderStatus = {
    RECEIVED: 'RECEIVED',
    ACK_SENT: 'ACK_SENT',
    NACK_SENT: 'NACK_SENT',
    PROCESSING: 'PROCESSING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    CONFIRMED: 'CONFIRMED',
    CANCEL_REQUESTED: 'CANCEL_REQUESTED',
    CANCELLED: 'CANCELLED',
    CANCEL_REJECTED: 'CANCEL_REJECTED',
    CANCELLED_SEND_FAILED: 'CANCELLED_SEND_FAILED',
    CANCEL_REJECTED_SEND_FAILED: 'CANCEL_REJECTED_SEND_FAILED',
    CANCEL_ERROR: 'CANCEL_ERROR',
    ON_CONFIRM_SENT: 'ON_CONFIRM_SENT',
    ON_CONFIRM_FAILED: 'ON_CONFIRM_FAILED',
    ON_CANCEL_SENT: 'ON_CANCEL_SENT',
    ON_CANCEL_FAILED: 'ON_CANCEL_FAILED',
    DELIVERED: 'Delivered',
    COMPLETED: 'Completed',
    SHIPPED: 'Shipped',
    CONFIRM_SENT: 'CONFIRM_SENT',
    FAILED: 'FAILED', 
    CANCELLED_BY_BUYER: 'CANCELLED_BY_BUYER',
    CANCELLED_BY_SELLER: 'CANCELLED_BY_SELLER',
  };
  
  export const AllowedCancelationReasons = new Set([
      '001', '002', '003', '004', '005',
      '006', '009', '010',
  ]);
  
  export const NonCancellableStates = [
      OrderStatus.DELIVERED,
      OrderStatus.COMPLETED,
      OrderStatus.CANCELLED,
  ];