// Test keys for development and testing
// These are sample keys and should never be used in production

export const TEST_KEYS = {
  'buyer-app-preprod-v2.ondc.org': {
    signing_public_key: 'MCowBQYDK2VwAyEAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    signing_private_key: 'MC4CAQAwBQYDK2VwBCIEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    encryption_public_key: 'MCowBQYDK2VwAyEAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    encryption_private_key: 'MC4CAQAwBQYDK2VwBCIEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  },
  'seller-app-preprod-v2.ondc.org': {
    signing_public_key: 'MCowBQYDK2VwAyEAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    signing_private_key: 'MC4CAQAwBQYDK2VwBCIEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    encryption_public_key: 'MCowBQYDK2VwAyEAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    encryption_private_key: 'MC4CAQAwBQYDK2VwBCIEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  }
};

export const getTestKey = (subscriberId) => {
  return TEST_KEYS[subscriberId] || null;
}; 