export const ALL_ATTRIBUTES = [
  "Category", "Brand", "Model", "Model Year", "Colour*", "Colour Name", "RAM", "RAM unit*", "ROM", "ROM unit*",
  "Storage", "Storage unit*", "Storage Type*", "Screen Size", "Primary Camera", "Secondary Camera",
  "CPU", "GPU", "Battery Capacity", "Playtime", "OS Type", "OS Version", "Connectivity*", "Form factor",
  "Compatible Devices*", "Special Feature*", "Includes", "Weight", "Length", "Breadth", "Height",
  "Refurbished", "Resolution", "Series", "Printer Output*", "Printer Speed", "Warranty", "Comments"
];


export const categoryAttributes = {
    "Mobile Phone": [
      { code: "brand", required: true },
      { code: "model", required: true },
      { code: "model_year", required: false },
      { code: "colour", required: true },
      { code: "ram", required: true },
      { code: "ram_unit", required: true },
      { code: "rom", required: false },
      { code: "rom_unit", required: false },
      { code: "storage", required: true },
      { code: "storage_unit", required: true },
      { code: "screen_size", required: false },
      { code: "primary_camera", required: false },
      {code: 'cpu', required: false},
      {code: 'gpu', required: false},
      { code: "battery_capacity", required: true },
      { code: "os_type", required: true },
      {code: 'os_version', required: false},
      { code: "connectivity", required: false },
      { code: "special_feature", required: true },
      { code: "weight", required: true },
      { code: "length", required: true },
      { code: "breadth", required: true },
      { code: "height", required: true },
      { code: "refurbished", required: false },
      { code: "resolution", required: false },
      { code: "warranty", required: false },
     
    ],
    "Smart Watch": [
      { code: "brand", required: true },
      { code: "model", required: true },
      { code: "model_year", required: false },
      { code: "colour", required: true },
      {code: "colour_name", required: true},
      { code: "screen_size", required: true },
      { code: "special_feature", required: true },
      { code: "weight", required: true },
      { code: "length", required: false },
      { code: "breadth", required: false },
      { code: "height", required: false },
      { code: "refurbished", required: false },
      { code: "warranty", required: false },

    ],
    "Headset": [
      { code: "brand", required: true },
      { code: "model", required: true },
      { code: "model_year", required: false },
      { code: "colour", required: true },
      { code: "special_feature", required: true },
      {code: "weight", required: true},
      {code: "length", required: true},
      {code: "series", required: true},
    ],
    "Laptop": [
      { code: "brand", required: true },
      { code: "model", required: false },
      { code: "model_year", required: false },
      { code: "colour", required: true },
      { code: "ram", required: true },
      { code: "ram_unit", required: true },
      { code: "rom", required: false },
      { code: "rom_unit", required: false },
      { code: "storage", required: true },
      { code: "storage_unit", required: true },
      { code: "storage_type", required: true },
      { code: "screen_size", required: true },
      { code: "special_feature", required: true },
      {code: 'cpu', required: true},
      {code: 'gpu', required: false},
      { code: "battery_capacity", required: false },
      { code: "os_type", required: true },
      {code: 'os_version', required: true },
      { code: "form_factor", required: false },
      { code: "includes", required: false },
      { code: "weight", required: true },
      { code: "length", required: true },
      { code: "breadth", required: true },
      { code: "height", required: true },
      { code: "refurbished", required: false },
      { code: "resolution", required: false },
      { code: "series", required: false },
      { code: "warranty", required: false },
    ],
    "Monitor": [
      { code: "brand", required: true },
      { code: "model", required: false },
      { code: "screen_size", required: true },
      { code: "special_feature", required: true },
      { code: "weight", required: true },
      { code: "length", required: true },
      { code: "breadth", required: true },
      { code: "height", required: true },
      { code: "refurbished", required: false },
      { code: "resolution", required: false },


      { code: "screen_type", required: false },
      { code: "brightness", required: false }, 
      { code: "contrast_ratio", required: false },
      { code: "response_time", required: false },
      { code: "color_support", required: false },

    ],
    "Tablet": [
      { code: "brand", required: true },
      { code: "model", required: true },
      { code: "model_year", required: false },
      { code: "ram", required: true },
      { code: "ram_unit", required: true },
      { code: "rom", required: false },
      { code: "rom_unit", required: false },
      { code: "storage", required: true },
      { code: "storage_unit", required: true },
      { code: "storage_type", required: true },
      { code: "screen_size", required: true },
      { code: "special_feature", required: true },
      {code: 'cpu', required: true},
      {code: 'gpu', required: false},
      { code: "battery_capacity", required: false },
      { code: "os_type", required: true },
      {code: 'os_version', required: true },
      { code: "includes", required: false },
      { code: "weight", required: true },
      { code: "length", required: true },
      { code: "breadth", required: true },
      { code: "height", required: true },
      { code: "refurbished", required: false },
      { code: "resolution", required: false },
      { code: "warranty", required: false },
      { code: "comments", required: false }
    ],
    "Audio Accessories": [
      { code: "brand", required: true },
      { code: "model", required: false },
      { code: "Connectivity", required: false },
      { code: "special_feature", required: true },
    ],
    "Camera": [
      { code: "brand", required: true },
      { code: "model", required: true },
      { code: "model_year", required: false },
      { code: "colour", required: false },
      { code: "colour_name", required: false },
      { code: "storage_unit", required: false },
      { code: "storage_type", required: true },
      { code: "primary_camera", required: true },
      { code: "battery_capacity", required: true },
      { code: "Connectivity", required: true },
      { code: "Compatible Devices", required: true },
      { code: "special_feature", required: true },
      { code: "weight", required: true },
      { code: "length", required: true },
      { code: "breadth", required: true },
      { code: "height", required: true },
      { code: "series", required: false },
      { code: "warranty", required: false },
    ],
    "Desktop": [
      { code: "brand", required: true },
      { code: "model", required: false },
      { code: "model_year", required: false },
      { code: "ram", required: true },
      { code: "ram_unit", required: true },
      { code: "rom", required: false },
      { code: "rom_unit", required: false },
      { code: "storage", required: true },
      { code: "storage_unit", required: true },
      { code: "storage_type", required: true },
      { code: "screen_size", required: true },
      { code: "special_feature", required: true },
      {code: 'cpu', required: true},
      {code: 'gpu', required: false},
      { code: "battery_capacity", required: false },
      { code: "os_type", required: true },
      {code: 'os_version', required: true },
      { code: "form_factor", required: false },
      { code: "includes", required: false },
      { code: "weight", required: true },
      { code: "length", required: true },
      { code: "breadth", required: true },
      { code: "height", required: true },
      { code: "refurbished", required: false },
      { code: "resolution", required: false },
      { code: "warranty", required: false },
    ],
  };
  